package day11_fake_file;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import utilities.TestBase;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TrendyolTest extends TestBase {

  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Test
  public void trendyol() {
    driver.get("https://www.trendyol.com/");
    driver.manage().window().setSize(new Dimension(1051, 806));
    driver.findElement(By.cssSelector(".homepage-popup-content:nth-child(4) img")).click();
    driver.findElement(By.cssSelector(".component-item:nth-child(12) img")).click();
    js.executeScript("window.scrollTo(0,400)");
    driver.findElement(By.cssSelector(".overlay")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".p-card-wrppr:nth-child(1) .image-overlay-body")).click();
    //vars.put("win725", waitForWindow(2000));
    driver.switchTo().window(vars.get("win725").toString());
    js.executeScript("window.scrollTo(0,177.60000610351562)");
    {
      WebElement element = driver.findElement(By.cssSelector(".add-to-basket-button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".add-to-basket-button-text")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".slc-img:nth-child(6) > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".slc-img:nth-child(6)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".slc-img:nth-child(10) > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".account-basket > .link-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Sepeti Onayla"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".i-trash")).click();
    driver.findElement(By.cssSelector(".ty-button:nth-child(2)")).click();
  }


}
